# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: metaverse
      MYSQL_USER: metaverse
      MYSQL_PASSWORD: metaverse
      MYSQL_DATABASE: metaverse
    # volumes:
    #   - my-datavolume:/var/lib/mysql
    ports:
      - 33060:33060
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # metaverse:
  #   build:
  #     # dockerfile:  #Dockerfile.dev
  #     context: .
  #     # Only will build development stage from dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - .env
  #   # Run a command against the development stage of the image
  #   command: yarn dev
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

volumes:
  my-datavolume:
