version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    hostname: localhost
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: metaverse
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  metaverse:
    build:
      context: .
      # Only will build development stage from dockerfile
      target: development
    volumes:
      - .:/usr/src
      # - /usr/src/app/node_modules
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: yarn start:dev
    links:
      - postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres-data:
