export enum EventsEnum {
  ALL_EVENT = 'ALL_EVENT',
  SENDER_AND_RECEIVER_EVENT = 'SENDER_AND_RECEIVER_EVENT',
  SENDER_ONLY_EVENT = 'SENDER-ONLY-EVENT',
  RECEIVER_ONLY_EVENT = 'RECEIVER_ONLY_EVENT',
  ZERO_TO_HUNDRED_$_EVENT = 'ZERO_TO_HUNDRED_EVENT',
  HUNDRED_TO_FIVE_HUNDRED_$_EVENT = 'HUNDRED_TO_FIVE_HUNDRED_EVENT',
  FIVE_HUNDRED_TO_TWO_THOUSAND_$_EVENT = 'FIVE_HUNDRED_TO_TWO_THOUSAND_EVENT',
  TWO_THOUSAND_TO_FIVE_THOUSAND_$_EVENT = 'TWO_THOUSAND_TO_FIVE_THOUSAND_EVENT',
  FIVE_THOUSAND_AND_ABOVE_$_EVENT = 'FIVE_THOUSAND_AND_ABOVE_EVENT',
}
