export enum MetaVerseEventsEnum {
  PROCESS_TRANSACTION_META_VERSE_EVENT = 'PROCESS_TRANSACTION_META_VERSE_EVENT',
  SEND_SOCKET_EVENTS = 'SEND_SOCKET_EVENTS',
  ZERO_TO_HUNDRED_META_VERSE_EVENT = 'ZERO_TO_HUNDRED_META_VERSE_EVENT',
  HUNDRED_TO_FIVE_HUNDRED_META_VERSE_EVENT = 'HUNDRED_TO_FIVE_HUNDRED_META_VERSE_EVENT',
  FIVE_HUNDRED_TO_TWO_THOUSAND_META_VERSE_EVENT = 'FIVE_HUNDRED_TO_TWO_THOUSAND_META_VERSE_EVENT',
  TWO_THOUSAND_TO_FIVE_THOUSAND_META_VERSE_EVENT = 'TWO_THOUSAND_TO_FIVE_THOUSAND_META_VERSE_EVENT',
  FIVE_THOUSAND_AND_ABOVE_META_VERSE_EVENT = 'FIVE_THOUSAND_AND_ABOVE_META_VERSE_EVENT',
}
