export enum RoomEnum {
  ALL_ROOM = 'ALL_ROOM',
  ZERO_TO_HUNDRED_$_ROOM = 'ZERO_TO_HUNDRED_ROOM',
  HUNDRED_TO_FIVE_HUNDRED_$_ROOM = 'HUNDRED_TO_FIVE_HUNDRED_ROOM',
  FIVE_HUNDRED_TO_TWO_THOUSAND_$_ROOM = 'FIVE_HUNDRED_TO_TWO_THOUSAND_ROOM',
  TWO_THOUSAND_TO_FIVE_THOUSAND_$_ROOM = 'TWO_THOUSAND_TO_FIVE_THOUSAND_ROOM',
  FIVE_THOUSAND_AND_ABOVE_$_ROOM = 'FIVE_THOUSAND_AND_ABOVE_ROOM',
}
