export enum SocketRoomEnum {
  ALL_ROOM = 'ALL_ROOM',
  SENDER_AND_RECEIVER_ROOM = 'SENDER_AND_RECEIVER_ROOM',
  SENDER_ONLY_ROOM = 'SENDER_ONLY_ROOM',
  RECEIVER_ONLY_ROOM = 'RECEIVER_ONLY_ROOM',
  ZERO_TO_HUNDRED_DOLLAR_ROOM = 'ZERO_TO_HUNDRED_DOLLAR_ROOM',
  ONE_HUNDRED_TO_FIVE_HUNDRED_DOLLAR_ROOM = 'ONE_HUNDRED_TO_FIVE_HUNDRED_DOLLAR_ROOM',
  FIVE_HUNDRED_TO_TWO_THOUSAND_DOLLAR_ROOM = 'FIVE_HUNDRED_TO_TWO_THOUSAND_DOLLAR_ROOM',
  TWO_THOUSAND_TO_FIVE_THOUSAND_DOLLAR_ROOM = 'TWO_THOUSAND_TO_FIVE_THOUSAND_DOLLAR_ROOM',
  FIVE_THOUSAND_AND_ABOVE_DOLLAR_ROOM = 'FIVE_THOUSAND_AND_ABOVE_DOLLAR_ROOM',
}
