export enum SocketEventsEnum {
  ALL_EVENT = 'ALL_EVENT',
  ZERO_TO_HUNDRED_DOLLAR_EVENT = 'ZERO_TO_HUNDRED_DOLLAR_EVENT',
  ONE_HUNDRED_TO_FIVE_HUNDRED_DOLLAR_EVENT = 'ONE_HUNDRED_TO_FIVE_HUNDRED_DOLLAR_EVENT',
  FIVE_HUNDRED_TO_TWO_THOUSAND_DOLLAR_EVENT = 'FIVE_HUNDRED_TO_TWO_THOUSAND_DOLLAR_EVENT',
  TWO_THOUSAND_TO_FIVE_THOUSAND_DOLLAR_EVENT = 'TWO_THOUSAND_TO_FIVE_THOUSAND_DOLLAR_EVENT',
  FIVE_THOUSAND_AND_ABOVE_DOLLAR_EVENT = 'FIVE_THOUSAND_AND_ABOVE_DOLLAR_EVENT',
}
